## Categories

We have got types column in the products DataFrame. With the help of this column we are creating our product categories. We are also using regex here. The type column has got 125 rows (these are our subcategories). From these we are creating 10 main product categories

In [1]:
import pandas as pd

In [2]:
# uploading the datasets from local
# products
path = './data/products_qa.csv'
products_qa_original = pd.read_csv(path)

# brands
path = './data/brands_cl_sonal.csv'
brands_cl_original = pd.read_csv(path)

# Creating a copy of the datasets. This ensures that our changes won't effect original DataFrames.
products_cg = products_qa_original.copy()
brands_cg = brands_cl_original.copy()

By using sample() and string methods to find the words that occur in each unique type, we were able to find the subcategories and then we are using the direct mapping for the most common and clear codes.

In [3]:
products_cg.loc[products_cg['type'] == '11865403'].sample(5)

,sku,name,desc,price,in_stock,type
3026,MOX0025,Moxie Man Picto Case iPhone 6 / 6S Transparent,Cover for iPhone 6 / 6S.,19.99,0,11865403
9039,NOM0029,Nomad iPhone Case X Clear Case brown leather,transparent cover with high quality leather wi...,39.95,0,11865403
1749,NTE0087,NewerTech NuGuard KX iPhone Case 6 / 6s Light ...,ultra tough for iPhone 6 and 6s. housing,60.99,0,11865403
5146,OTT0157,OtterBox iPhone Strada 8/7 leather case brown,Original leather case with cover and card slot...,49.99,0,11865403
3043,TUC0230,Housing Flex Elektro Tucano iPhone 6 / 6S Tran...,Cover for iPhone 6 / 6S.,16.90,0,11865403

In [4]:
type_mask = products_cg['type'] == '11865403'
(products_cg.loc[type_mask, 'name']
 .str.split()
 .explode()
 .value_counts()
 .head(15))

name
iPhone         1034
Case           1023
/               782
Plus            481
6               450
Black           323
7               245
6S              241
Apple           201
Leather         159
X               139
Transparent     121
Cover           117
Blue            112
6s              112
Name: count, dtype: int64

In [5]:
# creating category column
products_cg['category'] = ''
products_cg.head(5)

,sku,name,desc,price,in_stock,type,category
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401,
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387,
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230,
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,1,1364,

In [6]:
# direct mapping
type_to_category = {
    # cases & protection
    '11865403':	'cases & protection', # cases
    '12635403':	'cases & protection', # ipad cases and covers
    '13835403':	'cases & protection', # MacBook cases
    '13555403':	'cases & protection', # Screen Protectors
    '2449':	'cases & protection', # Apple Watch straps
    '1392':	'cases & protection', # Laptop cases and bags
    '5,49E+11':	'cases & protection', # Battery Cases
    '1231':	'cases & protection', # AppleCare Protection Plans
    '10230': 'cases & protection', # Laptop Bags & Cases
    '12575403':	'cases & protection', # keyboard cases
    '14035403':	'cases & protection', # screen protector and cases
    '5403':	'cases & protection', # ipad cases
    '2425':	'cases & protection', # Watch screen protector
    '2434':	'cases & protection', # apple watch cases

    # storage 
    '12175397': 'storage', #nas storages
    '11935397': 'storage', #Storage devices
    '1364': 'storage', #memory ram
    '1433': 'storage', #Memory Upgrade Kits
    '12215397': 'storage', #SSD storage
    '57445397': 'storage', #Flash Storage
    '12655397': 'storage', #Internal Storage
    '42945397': 'storage', #iPhone/iPad Flash Drives
    '1280': 'storage', #NAS storage
    '12755395': 'storage', #storage upgrade kit
    '1424': 'storage', #External Optical Drives

    # computers & laptops 
    '1282': 'computers & laptops', #Mac computers
    '5,74E+15': 'computers & laptops', #Desktop computers
    '1296': 'computers & laptops', #Computer monitors
    '1,02E+12': 'computers & laptops', #MacBook Pro
    '2158': 'computers & laptops', #Apple MacBook Pro
    '51902158': 'computers & laptops', #Apple Macbook Air
    '9,29E+11': 'computers & laptops', #Apple MacBook Pro
    '21622158': 'computers & laptops', #Second apple Mac mini
    '118692158': 'computers & laptops', #Apple iMac Pro
    '5,39E+11': 'computers & laptops', #Apple Macbook
    '2,16E+11': 'computers & laptops', #Apple imac
    '5,44E+11': 'computers & laptops', #Apple mac mini
    '5,43E+15': 'computers & laptops', #Second imac
    '51882158': 'computers & laptops', #imac
    '21632158': 'computers & laptops', #mac pro
    '2,17E+11': 'computers & laptops', #macbook
    '5,72E+15': 'computers & laptops', #second imac
    '5,45E+15': 'computers & laptops', #Apple Mac mini
    '51912158': 'computers & laptops', #Open Apple MacBook Pro

    # power, cables & connectivity 
    '12585395': 'power, cables & connectivity', #USB hubs and adapters
    '1325': 'power, cables & connectivity', #USB and Display Cables
    '1230': 'power, cables & connectivity', #cables and adapters
    '11434': 'power, cables & connectivity', #Apple adapter cable
    '12995397': 'power, cables & connectivity', #Docking Stations & USB Hubs
    '1334': 'power, cables & connectivity', #Networking 
    '5395': 'power, cables & connectivity', #Adapters
    '14365395': 'power, cables & connectivity', #adapters
    '13955395': 'power, cables & connectivity', #Adapters and Connectors
    '1515': 'power, cables & connectivity', #Power Banks
    '13615399': 'power, cables & connectivity', #Chargers and Charging Docks
    '24215399': 'power, cables & connectivity', #Charging Docks
    '13005399': 'power, cables & connectivity', #Power & Charging
    '5399': 'power, cables & connectivity', #Wireless Chargers

    # input & audio devices 
    '5384': 'input & audio devices', #Headphones & Earphones
    '5398': 'input & audio devices', #speakers
    '1405': 'input & audio devices', #Digital Drawing Tablets
    '1229': 'input & audio devices', #Stylus Pens
    '54025401': 'input & audio devices', #wireless keyboard
    '13855401': 'input & audio devices', #keyboard
    '1387': 'input & audio devices', #mouse
    '1375': 'input & audio devices', #USB Microphones
    '5401': 'input & audio devices', #Blutooth keyboard

    # mobile, wearables & smart devices 
    '11905404': 'mobile, wearables & smart devices', #Smart devices
    '24895185': 'mobile, wearables & smart devices', #Apple watch
    '24885185': 'mobile, wearables & smart devices', #Apple watch
    '5185': 'mobile, wearables & smart devices', #Apple watch
    '79201715': 'mobile, wearables & smart devices', #second ipod
    '113851714': 'mobile, wearables & smart devices', #Open ipad
    '24811716': 'mobile, wearables & smart devices', #iphone
    '113281716': 'mobile, wearables & smart devices', #iphone 8
    '51871714': 'mobile, wearables & smart devices', #ipad
    '11821715': 'mobile, wearables & smart devices', #Apple ipod
    '51601716': 'mobile, wearables & smart devices', #iphone
    '85651716': 'mobile, wearables & smart devices', #iphone
    '85641716': 'mobile, wearables & smart devices', #iphone
    '12141714': 'mobile, wearables & smart devices', #ipad
    '9094': 'mobile, wearables & smart devices', #Security Cameras
    '106431714': 'mobile, wearables & smart devices', #ipad pro
    '51861714': 'mobile, wearables & smart devices', #ipad pro
    '1714': 'mobile, wearables & smart devices', #ipad 
    '24821716': 'mobile, wearables & smart devices', #iphone
    '13621714': 'mobile, wearables & smart devices', #ipad mini
    '1716': 'mobile, wearables & smart devices', #iphone
    '11859': 'mobile, wearables & smart devices', #multi sensor
    '42931714': 'mobile, wearables & smart devices', #ipad
    '24861714': 'mobile, wearables & smart devices', #ipad mini
    '113291716': 'mobile, wearables & smart devices', #iphone
    '5404': 'mobile, wearables & smart devices', #Electronic Devices
    '113464259': 'mobile, wearables & smart devices', #Open Apple tv
    '4259': 'mobile, wearables & smart devices', #apple media player
    '12031714': 'mobile, wearables & smart devices', #ipad mini
    '21561716': 'accessories & miscellaneous', #iphone 6
    '21571716': 'accessories & miscellaneous', #Apple iPhone 6 Plus
    '113271716': 'accessories & miscellaneous', #iphone (old and new)
    '12051714': 'accessories & miscellaneous', #second ipad

    # accessories & miscellaneous 
    '12282': 'accessories & miscellaneous', #Travel support stand
    '8696': 'accessories & miscellaneous', #computer stand
    '15435404': 'accessories & miscellaneous', #Specialized Computer Accessories
    '1216': 'accessories & miscellaneous', #Device stands
    '5720': 'accessories & miscellaneous', #Phone Mounts and Stands
    '5405': 'accessories & miscellaneous', #Phone Armbands
    '1404': 'accessories & miscellaneous', #NAS Accessories
    '12355400': 'accessories & miscellaneous', #Computer & Electronics Accessories
    '12285400': 'accessories & miscellaneous', #Miscellaneous Accessories
    '101781405': 'accessories & miscellaneous', #Digital Drawing Accessories
    '12085400': 'accessories & miscellaneous', #Device Care Accessories
    '54864259': 'accessories & miscellaneous', #Apple remote

    # software & repair sevices   
    '1,44E+11': 'software & repair sevices', #Repair Services
    '1416': 'software & repair sevices', #software
    '20642062': 'software & repair sevices', #installation services

    # repair tools & parts 
    '21485407': 'repair tools & parts', #fixit replacement parts
    '12645406': 'repair tools & parts', #Fixit repair tools
    '14305406': 'repair tools & parts', #Fixit repair tools
    '1276': 'repair tools & parts', #Computer Expansion Cards
    '5407': 'repair tools & parts', #fixit adhesive strip
    '5406': 'repair tools & parts', #Fixit kit
    '10142': 'repair tools & parts', #Replacement Batteries
    '21535407': 'repair tools & parts', #iPad Replacement Parts
    '54085407': 'repair tools & parts', #Mac Replacement Parts
}

products_cg['category'] = products_cg['type'].map(type_to_category)

We have got 783 rows of products in type (1298), which are open box products and it contains products from various categories. So we need to make use of regex to categorize it

In [7]:
import re
def category_from_text(row):
    text = f"{row.get('name', '')}{row.get('desc', '')}".lower()

    if re.search(r'case|protective|screen protector|bag|sleeve|cover|watch strap',text):
        return 'cases & protection'
    elif re.search(r'storage|memory|flash storage|storage upgrade|hard drive|hard disk|usb|ssd|pendrive|raid|server|synology',text):
        return 'storage'
    elif re.search(r'adapter|cable|charger|powerbank|hub|station|dock|wireless|connector|ethernet|converter|hdmi',text):
        return 'power, cables & connectivity'
    elif re.search(r'headphone|earphone|headset|mouse|keyboard|drawing|stylus|pointer|speaker|keypad|hotspot|graphic',text):
        return 'input & audio devices'
    elif re.search(r'software|service|repair service',text):
        return 'software & repair sevices'
    elif re.search(r'ifixit|repair|kit|replacement|expansion',text):
        return 'repair tools & parts'
    elif re.search(r'stand|support|armband|accessories|mount|drawing|device care|remote|strips|color manager|mat',text):
        return 'accessories & miscellaneous'
    elif re.search(r'imac|macbook|mac mini|monitor|desktop',text):
        return 'computers & laptops'   
    elif re.search(r'watch|iphone|ipod|ipad|smart|sensor|camera|robot|amplifier|bulb',text):
        return 'mobile, wearables & smart devices'

In [8]:
# calling the function
type_mask = products_cg['type'] == '1298'

products_cg.loc[type_mask, 'category'] = (
    products_cg.loc[type_mask]
    .apply(category_from_text, axis=1)
)

In [9]:
type_mask = products_cg['type'] == '1298'
products_cg.loc[type_mask, 'category'].isna().sum()

np.int64(0)

there are also some products that were not categorized because the type colum in these rows are empty. These can also be categorized using the above method. We are calling same function but with another mask

In [10]:
products_cg['type'].isna().sum(), products_cg['category'].isna().sum()

(np.int64(46), np.int64(46))

In [11]:
null_mask = products_cg['type'].isna()
products_cg.loc[null_mask, 'category'] = (
    products_cg.loc[null_mask]
    .apply(category_from_text, axis=1)
)

In [12]:
products_cg['category'].isna().sum()

np.int64(0)

we are merging the products table with the brands table and to do so we are first extracting the three letters from sku (thus creating primary and foreign key)

In [13]:
products_cg['brands'] = products_cg['sku'].str[:3]

In [14]:
products_brands_cg = products_cg.merge(brands_cg, left_on='brands', right_on='short', how='left')

In [17]:
products_brands_cg.to_csv('./data/products_brands_cg.csv', index=False)