In [72]:
import pandas as pd

In [73]:
pd.reset_option('all')

/var/folders/sk/vjb6l5ys1llg_86tjfj_22900000gn/T/ipykernel_1278/2786130087.py:1: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.reset_option('all')
/var/folders/sk/vjb6l5ys1llg_86tjfj_22900000gn/T/ipykernel_1278/2786130087.py:1: Pandas4Warning: The 'mode.copy_on_write' option is deprecated. Copy-on-Write can no longer be disabled (it is always enabled with pandas >= 3.0), and setting the option has no impact. This option will be removed in pandas 4.0.
  pd.reset_option('all')

In [74]:
# uploading cleaned datasets from local
# orders
orders_qa_original = pd.read_csv('./data/orders_qa.csv', parse_dates=['created_date'])

# orderlines
orderlines_qa_original = pd.read_csv('./data/orderlines_qa.csv', parse_dates=['date'])

# products
products_brands_cg_original = pd.read_csv('./data/products_brands_cg.csv')

Creating a copy of the datasets. This ensures that our changes won't effect original DataFrames.

In [75]:
orders_an = orders_qa_original.copy()
orderlines_an = orderlines_qa_original.copy()
products_brands_an = products_brands_cg_original.copy()

In [76]:
orders_an.sample(5)

       order_id        created_date  total_paid      state
4461     317578 2017-01-30 15:46:37       89.99  Completed
9177     355583 2017-05-13 22:28:01       69.47  Completed
27173    450017 2017-11-27 23:47:50      126.90  Completed
39507    518383 2018-02-28 11:04:06       84.77  Completed
14594    385575 2017-08-02 22:31:47      369.00  Completed

In [77]:
orderlines_an.sample(5)

,id,order_id,product_quantity,sku,unit_price,date,unit_price_total
37398,1491847,461089,1,WAC0231,71.99,2017-12-12 20:23:55,71.99
29964,1419212,430623,1,ADN0049,16.99,2017-11-21 20:59:41,16.99
44898,1559880,490609,1,REP0270,69.90,2018-01-14 18:17:41,69.90
6939,1175047,321678,1,OWC0062,9.99,2017-02-09 10:11:25,9.99
36154,1474568,454419,1,SAT0030,9.99,2017-12-03 14:53:20,9.99

In [78]:
products_brands_an.sample(5)

,sku,name,desc,price,in_stock,type,category,brands,short,long
2395,MUV0161,"Muvit Bracelet Universal Fino 4-47 ""Black + Sp...",sporty and comfortable armband for iPhone 5 / ...,19.95,0,5405,accessories & miscellaneous,MUV,MUV,Muvit
5315,WAC0204,Wacom Bamboo Stylus Duo 4 White,digital pen and pencil with built-in triangula...,29.90,1,1229,input & audio devices,WAC,WAC,Wacom
3020,JAW0043,Jawbone UP3 Activity Monitor Blue,Bracelet that records sleep data feed and move...,179.99,0,11905404,"mobile, wearables & smart devices",JAW,JAW,Jawbone
4933,GTE0059,G-Technology G-DRIVE mobile USB 3.0 1TB 7200rp...,1TB external hard drive with aluminum housing ...,104.99,0,11935397,storage,GTE,GTE,G-Technology
6104,STA0045,Startech charging cable 2m Thunderbolt 3 20Gb ...,Cable length 2 meters connection Thunderbolt T...,49.99,1,1325,"power, cables & connectivity",STA,STA,Startech

In [79]:
products_brands_an['sku'].nunique()

9992

first let us find the total products that we have after the cleaning. We are also finding no of products that are discounted in this. We should find the same numbers in each category

In [80]:
orderlines_products = orderlines_an.merge(products_brands_an, on='sku')

In [81]:
orderlines_products['discount'] = orderlines_products['price']-orderlines_products['unit_price']
orderlines_products

,id,order_id,product_quantity,sku,unit_price,date,unit_price_total,name,desc,price,in_stock,type,category,brands,short,long,discount
0,1119116,299545,1,OWC0100,47.49,2017-01-01 01:46:16,47.49,OWC In-line Digital Temperature Sensor Kit HDD...,Kit temperature sensor for HDD iMac 21 inch an...,60.99,1,12755395,storage,OWC,OWC,OWC,13.50
1,1119119,299546,1,IOT0014,18.99,2017-01-01 01:50:34,18.99,iOttie Easy View 2 Car Black Support,IPhone car holder 7 plus / 7/6 Plus / 6 / 5s /...,22.95,0,5720,accessories & miscellaneous,IOT,IOT,iOttie,3.96
2,1119120,295347,1,APP0700,72.19,2017-01-01 01:54:11,72.19,Apple 85W MagSafe 2 charger MacBook Pro screen...,Apple MagSafe 2 Charger for MacBook Pro 15-inc...,89.00,1,13005399,"power, cables & connectivity",APP,APP,Apple,16.81
3,1119134,299556,1,CRU0039-A,60.90,2017-01-01 02:20:14,60.90,(Open) Crucial 240GB SSD 7mm BX200,SSD hard drive and high-speed performance with...,76.99,0,1298,storage,CRU,CRU,Crucial,16.09
4,1119145,299561,1,PEB0015,142.49,2017-01-01 02:38:50,142.49,Pebble Smartwatch Time Steel Black,Bluetooth Smart Watch with steel case leather ...,299.99,0,11905404,"mobile, wearables & smart devices",PEB,PEB,Pebble,157.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53226,1649447,527035,1,APP0698,9.99,2018-03-14 11:42:41,9.99,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1,1230,"power, cables & connectivity",APP,APP,Apple,15.01
53227,1649512,527070,2,APP0698,9.99,2018-03-14 11:49:01,19.98,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1,1230,"power, cables & connectivity",APP,APP,Apple,15.01
53228,1649522,527074,2,APP0698,9.99,2018-03-14 11:49:36,19.98,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1,1230,"power, cables & connectivity",APP,APP,Apple,15.01
53229,1649565,527096,3,APP0698,9.99,2018-03-14 11:54:35,29.97,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1,1230,"power, cables & connectivity",APP,APP,Apple,15.01
53230,1649593,527112,1,APP0698,9.99,2018-03-14 11:58:13,9.99,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1,1230,"power, cables & connectivity",APP,APP,Apple,15.01

In [82]:
orderlines_products.sample(5)

,id,order_id,product_quantity,sku,unit_price,date,unit_price_total,name,desc,price,in_stock,type,category,brands,short,long,discount
26061,1383800,415238,1,ELA0008,49.99,2017-10-20 21:42:31,49.99,elago L3 MacBook Aluminum Stand Space Gray,Aluminum support with antiskid and cable manag...,55.00,0,8696,accessories & miscellaneous,ELA,ELA,Elago,5.01
21136,1327430,393945,1,GRT0364,26.99,2017-08-29 16:25:41,26.99,Adidas armband Griffin iPhone 7 Plus / 6s Plus...,Bracelet sport and activity screensaver for iP...,29.99,0,5405,accessories & miscellaneous,GRT,GRT,Griffin,3.00
14281,1276463,369732,1,ELA0025,15.99,2017-06-28 00:10:47,15.99,elago Lightning Aluminum Cable 1m Rosa,Charging cable connection and synchronization ...,17.99,1,1230,"power, cables & connectivity",ELA,ELA,Elago,2.00
6773,1173846,321103,1,FCM0005-2,37.99,2017-02-07 20:45:21,37.99,Mac memory FCM 4GB (2x2GB) SO-DIMM DDR2 800 MHz,RAM 4GB (2x2gb) iMac with Intel Core 2 Duo (Pe...,60.00,0,1364,storage,FCM,FCM,FCM,22.01
14523,1278346,370636,1,WDT0249,229.99,2017-06-30 11:34:47,229.99,"WD Red 6TB 35 ""Mac PC hard drive and NAS",Western Digital hard drive designed for NAS 6T...,255.00,1,12655397,storage,WDT,WDT,Western Digital,25.01

In [83]:
orderlines_products['discount'].describe()

count    53231.000000
mean        26.116673
std         45.545881
min       -170.990000
25%          5.250000
50%         15.000000
75%         31.000000
max       1320.000000
Name: discount, dtype: float64

In [84]:
negative_order_id = orderlines_products.loc[(orderlines_products['discount'] < 0), 'order_id']

In [85]:
orders_an = orders_an.loc[~orders_an['order_id'].isin(negative_order_id)]

In [86]:
orderlines_an = orderlines_an.loc[~orderlines_an['order_id'].isin(negative_order_id)]

In [87]:
orderlines_products = orderlines_products.loc[~orderlines_products['order_id'].isin(negative_order_id)]

In [88]:
orders_an['order_id'].nunique(), orderlines_an['order_id'].nunique()

(39476, 39476)

In [89]:
orderlines_products['short'].isna().sum()

np.int64(36)

In [90]:
orderlines_products = orderlines_products[['order_id', 'sku', 'product_quantity', 'date', 'unit_price', 'price', 'discount', 'category', 'brands']]

In [91]:
orderlines_products

,order_id,sku,product_quantity,date,unit_price,price,discount,category,brands
0,299545,OWC0100,1,2017-01-01 01:46:16,47.49,60.99,13.50,storage,OWC
1,299546,IOT0014,1,2017-01-01 01:50:34,18.99,22.95,3.96,accessories & miscellaneous,IOT
2,295347,APP0700,1,2017-01-01 01:54:11,72.19,89.00,16.81,"power, cables & connectivity",APP
3,299556,CRU0039-A,1,2017-01-01 02:20:14,60.90,76.99,16.09,storage,CRU
4,299561,PEB0015,1,2017-01-01 02:38:50,142.49,299.99,157.50,"mobile, wearables & smart devices",PEB
...,...,...,...,...,...,...,...,...,...
53226,527035,APP0698,1,2018-03-14 11:42:41,9.99,25.00,15.01,"power, cables & connectivity",APP
53227,527070,APP0698,2,2018-03-14 11:49:01,9.99,25.00,15.01,"power, cables & connectivity",APP
53228,527074,APP0698,2,2018-03-14 11:49:36,9.99,25.00,15.01,"power, cables & connectivity",APP
53229,527096,APP0698,3,2018-03-14 11:54:35,9.99,25.00,15.01,"power, cables & connectivity",APP
53230,527112,APP0698,1,2018-03-14 11:58:13,9.99,25.00,15.01,"power, cables & connectivity",APP

In [94]:
orderlines_products['sku'].nunique()

5013

In [95]:
orderlines_products['product_quantity'].sum()

np.int64(57334)

In [96]:
discount_mask = ~(orderlines_products['discount'] == 0)
orderlines_products.loc[discount_mask, 'product_quantity'].sum()

np.int64(54880)

In [98]:
# percentage of products discounted
((orderlines_products.loc[discount_mask, 'product_quantity'].sum() / orderlines_products['product_quantity'].sum()) * 100).round(2)

np.float64(95.72)

In [100]:
orderlines_products.groupby('category').size()

category
accessories & miscellaneous           1426
cases & protection                    9864
computers & laptops                   1680
input & audio devices                 6499
mobile, wearables & smart devices     6383
power, cables & connectivity          8422
repair tools & parts                  2028
software & repair sevices               80
storage                              14492
dtype: int64

In [101]:
orderlines_products.groupby('category')['product_quantity'].sum()

category
accessories & miscellaneous           1563
cases & protection                   10462
computers & laptops                   1911
input & audio devices                 7169
mobile, wearables & smart devices     7037
power, cables & connectivity          9699
repair tools & parts                  2135
software & repair sevices               83
storage                              17275
Name: product_quantity, dtype: int64

In [102]:
orderlines_products.loc[discount_mask].groupby('category')['product_quantity'].sum()

category
accessories & miscellaneous           1438
cases & protection                   10262
computers & laptops                   1900
input & audio devices                 6525
mobile, wearables & smart devices     6721
power, cables & connectivity          9304
repair tools & parts                  1803
software & repair sevices               55
storage                              16872
Name: product_quantity, dtype: int64

In [104]:
# percentage
((orderlines_products.loc[discount_mask].groupby('category')['product_quantity'].sum() / orderlines_products.groupby('category')['product_quantity'].sum())* 100).round(2)

category
accessories & miscellaneous          92.00
cases & protection                   98.09
computers & laptops                  99.42
input & audio devices                91.02
mobile, wearables & smart devices    95.51
power, cables & connectivity         95.93
repair tools & parts                 84.45
software & repair sevices            66.27
storage                              97.67
Name: product_quantity, dtype: float64